name: build-push-image
description: "Build and push multi-arch image to GHCR using docker buildx"
inputs:
  name:
    description: "Name of image to build."
    required: true
  platforms:
    description: "Comma separated list of platforms to build"
    required: false
    default: 'linux/amd64'
  context:
    description: "Context directory for build containing Dockerfile"
    required: false
    default: './'
  file:
    description: "Path to Dockerfile"
    required: false
    default: './Dockerfile'
  latest:
    description: "Set latest tag to this image"
    required: false
    default: 'false'
  username:
    description: "Username for ghcr.io"
    required: true
  password:
    description: "Password for ghcr.io"
    required: true
runs:
  using: "composite"
  steps:
    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/joberly/${{ inputs.name }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest,enable=${{ inputs.latest == 'true' }}
    - name: Start QEMU for building multi-arch images
      uses: docker/setup-qemu-action@v2
    - name: Start Docker buildx builder
      uses: docker/setup-buildx-action@v2
    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build ${{ inputs.name }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: 'true'
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
