swagger: "2.0"
info:
    title: Demo Service
    description: Demonstration Go Service
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /rand:
        get:
            tags:
                - demo
            summary: rand demo
            operationId: demo#rand
            parameters:
                - name: min
                  in: query
                  required: false
                  type: integer
                  format: int64
                - name: max
                  in: query
                  required: false
                  type: integer
                  format: int64
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DemoRandResponseBody'
                "400":
                    description: Invalid arguments to API
                    schema:
                        $ref: '#/definitions/DemoRandInvalidArgumentsResponseBody'
            schemes:
                - http
definitions:
    DemoRandInvalidArgumentsResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: rand_invalid_arguments_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    DemoRandResponseBody:
        title: 'Mediatype identifier: application/vnd.demo.rand-result; view=default'
        type: object
        properties:
            result:
                type: integer
                example: 1873507761458882011
                format: int64
        description: RandResponseBody result type (default view)
        example:
            result: 1666936218841511885
